// <auto-generated />
using System;
using Maran.Modules.Sftp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maran.Modules.Sftp.Persistence.Migrations
{
    [DbContext(typeof(SftpDbContext))]
    [Migration("20260901231407_InitialSftpSchema")]
    partial class InitialSftpSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sftp")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maran.Modules.Sftp.Domain.Entities.SftpUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_SftpUsers_AccountId");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("IX_SftpUsers_FullName");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_SftpUsers_AccountId_Name");

                    b.ToTable("SftpUsers", "sftp");
                });
#pragma warning restore 612, 618
        }
    }
}
