// <auto-generated />
using System;
using Maran.Modules.Monitoring.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maran.Modules.Monitoring.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    partial class MonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maran.Modules.Monitoring.Common.MetricBucketRow", b =>
                {
                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskTotalBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskUsedBytes")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastCapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LoadAverage1m")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryTotalBytes")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryUsedBytes")
                        .HasColumnType("double precision");

                    b.Property<long>("NetworkRxBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkTxBytes")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Maran.Modules.Monitoring.Domain.Entities.AlertState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveBreaches")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFiring")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Subject")
                        .IsUnique()
                        .HasDatabaseName("IX_AlertStates_Kind_Subject");

                    b.ToTable("AlertStates", "monitoring");
                });

            modelBuilder.Entity("Maran.Modules.Monitoring.Domain.Entities.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("DiskTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("DiskUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<double>("LoadAverage1m")
                        .HasColumnType("double precision");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkRxBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NetworkTxBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("IX_Samples_CapturedAt");

                    b.ToTable("Samples", "monitoring");
                });
#pragma warning restore 612, 618
        }
    }
}
