<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Maran.Host\Maran.Host.csproj" />
    <ProjectReference Include="..\..\src\Maran.Sdk\Maran.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Maran.SharedKernel\Maran.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Maran.Agent.Client\Maran.Agent.Client.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Accounts\Maran.Modules.Accounts.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Identity\Maran.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Sites\Maran.Modules.Sites.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Ssl\Maran.Modules.Ssl.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Databases\Maran.Modules.Databases.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Sftp\Maran.Modules.Sftp.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Firewall\Maran.Modules.Firewall.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Cron\Maran.Modules.Cron.csproj" />
    <ProjectReference Include="..\..\src\Maran.Modules\Tasks\Maran.Modules.Tasks.csproj" />
  </ItemGroup>

</Project>
