import { expect, test, type APIRequestContext, type Page } from '@playwright/test'

/**
 * The golden path, spec §16: install, an account, a site on it, and a certificate for that
 * site — driven in a real browser against the panel's OWN API and a REAL root agent on a real
 * host. This plan owns those four steps; files, databases, cron and suspend arrive with later
 * plans and are out of scope here.
 *
 * This is the only test in the repository that proves the pieces work TOGETHER, so it stubs
 * nothing. Every other spec under `e2e/` installs `page.route` fakes and is therefore blind to
 * the one failure mode that has cost this plan the most: a piece that is correct on its own and
 * is never reached, registered or wired by the thing that assembles it. Three defects of exactly
 * that shape survived 758 backend tests, 434 agent tests and 98 stubbed browser tests, and were
 * found by the first run of this file's manual walk-through. A fake here would make this spec
 * another instance of the problem it exists to catch, so there are none.
 *
 * ## What it needs, and why it refuses rather than skips silently
 *
 * It runs only when `E2E_REAL_BACKEND=1` — the flag `playwright.config.ts` already documents for
 * "exercise a real running backend". Without the flag the spec is annotated and skipped, because
 * the default suite deliberately runs with no backend at all. WITH the flag, an unreachable stack
 * is a FAILURE and never a skip: `rules/testing.md` treats "nothing ran" as a failure to verify,
 * and a golden path that quietly skips is worse than one that is missing.
 *
 * ## Running it
 *
 * ```bash
 * source scripts/dev
 * maran dev                                     # database, API and SPA
 * openssl req -x509 -newkey rsa:2048 -nodes -days 30 \
 *   -keyout gp.key -out gp.crt -subj "/CN=golden-path.example.com"
 * cd frontend
 * MARAN_E2E_CERTIFICATE_PEM="$(cat ../gp.crt)" MARAN_E2E_PRIVATE_KEY_PEM="$(cat ../gp.key)" \
 *   E2E_REAL_BACKEND=1 npx playwright test e2e/golden-path
 * ```
 *
 * The certificate material is generated by the caller rather than by this file: Node's `crypto`
 * cannot mint an X.509 certificate, and pulling in a library to do it would put a dependency in
 * the SPA's tree for one test. The subject does NOT have to match this run's domain, because the
 * panel does not check that it does — one pair therefore serves every run, and the missing check
 * is recorded as an open item rather than relied on here.
 *
 * `maran dev` does NOT start an agent, and the panel's account and site operations reach the host
 * before they touch the database — so without one this spec stops at account creation with the
 * agent's own error. To drive the whole path, run the agent inside a polygon container and point
 * the panel at its socket (`docker/README.md` builds the images):
 *
 * ```bash
 * mkdir -p /run/user/"$(id -u)"/maran
 * docker run -d --name maran-golden -p 8081:80 \
 *   -v "$PWD/agent/target/debug/maran-agent:/usr/local/bin/maran-agent:ro" \
 *   -v "/run/user/$(id -u)/maran:/run/maran" maran-polygon-ubuntu24 sleep infinity
 * docker exec maran-golden sh -c 'mkdir -p /run/maran/php; nginx; \
 *   maran-agent --socket /run/maran/agent.sock --allow-uid '"$(id -u)"' &'
 * docker exec maran-golden chgrp "$(id -g)" /run/maran/agent.sock
 * # then set Agent__SocketPath=/run/user/<uid>/maran/agent.sock in .env and restart `maran dev`
 * ```
 *
 * The socket's group ownership is not a workaround for the polygon: on a server the installer
 * gives it to the `panel` group for exactly this reason, so this reproduces the production
 * arrangement rather than relaxing it.
 *
 * ## What this spec deliberately does NOT assert, and why
 *
 * - **That the site answers over HTTPS.** The browser here reaches the SPA, not the polygon's
 *   nginx, and the site has no content to serve until somebody puts a file in its document root —
 *   which no screen in this release does. That nginx can now READ a document root at all is
 *   proved where it can be: `a_real_nginx_serves_a_site_out_of_the_accounts_own_home` in the
 *   agent's polygon suite fetches a real page over a real socket, on both families.
 * - **A real Let's Encrypt issuance.** There is no public domain pointing at the machine running
 *   this and no inbound port 80, so HTTP-01 cannot be satisfied and NOTHING here fakes a success.
 *   The ACME client does reach the authority — directory, nonce and a signed `newAccount` — and
 *   stops at registration; the issuance half has never spoken to a CA and this spec does not
 *   pretend otherwise.
 */

/**
 * The Node environment this spec is configured through.
 *
 * Declared here rather than pulled in with `@types/node`: `tsconfig.app.json` covers `src/` and
 * `e2e/` together and targets the DOM, so adding Node's global types to it would put `process`,
 * `Buffer` and the rest in scope for every SPA source file — a much larger change than one test
 * needs, and one that makes a Node-only global look available to code that runs in a browser.
 * This is the only spec that takes configuration from the environment, because it is the only one
 * that talks to something outside the browser.
 */
declare const process: { readonly env: Readonly<Record<string, string | undefined>> }

/** Set to `1` to run this spec against a live stack; unset, the spec is skipped as annotated. */
const REAL_BACKEND = process.env.E2E_REAL_BACKEND === '1'

/**
 * One-time setup token, matching `.env.example`'s development value. Not a secret: it is refused
 * the moment the panel has a user, whatever it is set to, and a server's token is generated by
 * the installer and never leaves it.
 */
const SETUP_TOKEN = process.env.MARAN_E2E_SETUP_TOKEN ?? 'dev-setup-token'

/** Administrator the spec signs in as, created by the setup step on a panel that has no user. */
const ADMIN_USERNAME = 'admin'

/** The administrator's password. A development value against a local panel, never a server one. */
const ADMIN_PASSWORD = process.env.MARAN_E2E_ADMIN_PASSWORD ?? 'GoldenPath!2026aA'

/**
 * Longest this spec waits for one host-touching step. Account and site creation fork, drop
 * privileges, run `useradd`, render a vhost and make nginx validate it, which is slower than any
 * stubbed screen — and every wait here is bounded, because an unbounded one turns a broken stack
 * into a hung run that gets blamed on the runner.
 */
const HOST_OPERATION_TIMEOUT = 30_000

/** Suffix making this run's account and site unique, so the spec is re-runnable against one panel. */
const RUN_ID = `${Date.now().toString(36)}`

/** Linux-username-safe account name for this run. */
const ACCOUNT_NAME = `gp${RUN_ID}`

/** Domain this run's site is created for. `example.com` is reserved and resolves for nobody. */
const SITE_DOMAIN = `${ACCOUNT_NAME}.example.com`

/**
 * Fails loudly when the stack this spec needs is not there.
 *
 * Asked for with `E2E_REAL_BACKEND=1`, an unreachable API is a failure to verify and not an
 * absence of work: reporting it as a skip is the same defect as reading "no tests found" as a
 * pass.
 * @param request Playwright's API request context, pointed at the SPA's origin.
 * @returns Resolves when the panel's health endpoint answers.
 */
const requireLiveStack = async (request: APIRequestContext): Promise<void> => {
  const response = await request.get('/health', { timeout: HOST_OPERATION_TIMEOUT })
  expect(
    response.ok(),
    'E2E_REAL_BACKEND=1 was set but the panel did not answer /health — start it with `maran dev`',
  ).toBe(true)

  const health = (await response.json()) as { agent?: string; database?: string }
  expect(health.database, 'the panel cannot reach its database').toBe('reachable')
  expect(
    health.agent,
    'no agent is connected: accounts and sites reach the host first, so the path cannot run — ' +
      'see this file for the polygon harness',
  ).toBe('connected')
}

/**
 * Puts the panel into a signed-in browser session, completing first-run setup when the panel has
 * no administrator yet.
 *
 * The setup half is the "install" step of spec §16's path: it is skipped only when a previous run
 * already performed it against this database, which is what makes the spec re-runnable without a
 * fresh database.
 * @param page The browser page to drive.
 * @param request The same origin's API context, used to ask whether setup is still open.
 * @returns Resolves once the panel's shell is on screen for a signed-in administrator.
 */
const signIn = async (page: Page, request: APIRequestContext): Promise<void> => {
  const state = await request.get('/api/v1/setup/state', { timeout: HOST_OPERATION_TIMEOUT })
  const isComplete = state.ok() ? ((await state.json()) as { isComplete: boolean }).isComplete : true

  if (!isComplete) {
    await page.goto(`/setup?token=${SETUP_TOKEN}`)
    await page.getByRole('textbox', { name: 'Username' }).fill(ADMIN_USERNAME)
    await page.getByRole('textbox', { name: 'Email' }).fill('admin@example.com')
    await page.getByRole('textbox', { name: 'Password', exact: true }).fill(ADMIN_PASSWORD)
    await page.getByRole('textbox', { name: 'Confirm password' }).fill(ADMIN_PASSWORD)
    await page.getByRole('button', { name: 'Create administrator' }).click()
    await expect(page.getByRole('heading', { level: 2, name: 'Sign in' })).toBeVisible({
      timeout: HOST_OPERATION_TIMEOUT,
    })
  }

  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Username' }).fill(ADMIN_USERNAME)
  await page.getByRole('textbox', { name: 'Password' }).fill(ADMIN_PASSWORD)
  await page.getByRole('button', { name: 'Sign in' }).click()

  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible({
    timeout: HOST_OPERATION_TIMEOUT,
  })
}

/**
 * Picks one option from one of the panel's comboboxes.
 *
 * The panel's select is a custom listbox, not a native `<select>` — `selectOption` does nothing
 * to it, silently, which is the kind of no-op that turns into a confusing failure three
 * assertions later. Opening it and clicking the option is what an operator does.
 * @param page The browser page to drive.
 * @param label The combobox's accessible name.
 * @param option Pattern the option's text must match.
 * @returns Resolves once the option has been chosen.
 */
const chooseOption = async (page: Page, label: string, option: RegExp): Promise<void> => {
  await page.getByRole('combobox', { name: label }).click()
  await page.getByRole('option', { name: option }).click({ timeout: HOST_OPERATION_TIMEOUT })
}

test.describe('the golden path: install, account, site, certificate', () => {
  test.skip(
    !REAL_BACKEND,
    'needs a live stack: run `maran dev` (plus an agent) and set E2E_REAL_BACKEND=1',
  )

  // One ordered story, not four independent tests: each step consumes what the last one created
  // on a real host, and running them in isolation would mean creating and deleting a Linux user
  // four times to assert one screen apiece.
  test.describe.configure({ mode: 'serial' })

  test('an operator installs the panel, and creates an account, a site and a certificate', async ({
    page,
    request,
  }) => {
    // A vhost render, an nginx validation and two host operations, in one browser story.
    test.setTimeout(180_000)

    await requireLiveStack(request)
    await signIn(page, request)

    // --- the account -------------------------------------------------------------------------
    await page.goto('/accounts/new')
    await page.getByRole('textbox', { name: 'Name' }).fill(ACCOUNT_NAME)
    await page.getByRole('textbox', { name: 'Primary domain' }).fill(SITE_DOMAIN)
    // The plans are read from the panel, so an empty list here means nothing seeded them — which
    // is worth failing on explicitly, because a fresh installation with no plan cannot create any
    // account at all and the form gives no hint why.
    await page.getByRole('combobox', { name: 'Plan ID' }).click()
    const plans = page.getByRole('option')
    await expect(plans, 'this panel has no plans, so no account can be created').not.toHaveCount(0)
    await plans.first().click()
    await page.getByRole('button', { name: 'Create account' }).click()

    // The list is the operator's own confirmation, and it is read back from the panel rather than
    // from the response the form received: a row here means the account survived the round trip.
    await expect(page).toHaveURL(/\/accounts/, { timeout: HOST_OPERATION_TIMEOUT })
    await expect(page.getByRole('link', { name: ACCOUNT_NAME })).toBeVisible({
      timeout: HOST_OPERATION_TIMEOUT,
    })

    // --- the site ----------------------------------------------------------------------------
    await page.goto('/sites/new')

    // The account list is loaded from the panel, so the option only exists because the account
    // above really was created — no fixture puts it here.
    await chooseOption(page, 'Account', new RegExp(`^${ACCOUNT_NAME}\\b`))
    await page.getByRole('textbox', { name: 'Domain' }).fill(SITE_DOMAIN)
    await chooseOption(page, 'Backend', /^PHP$/)

    // The PHP versions come from the agent asking the real host what is installed, so this
    // listbox is empty on a machine with no php-fpm — which is a fact about the server, and the
    // panel says so rather than offering a version it cannot honour. Asserted before it is used,
    // so "no versions" reports itself instead of surfacing as a mysterious click timeout.
    const phpVersions = page.getByRole('combobox', { name: 'PHP version' })
    await expect(phpVersions).toBeVisible({ timeout: HOST_OPERATION_TIMEOUT })
    await phpVersions.click()
    const offered = page.getByRole('option')
    await expect(
      offered,
      'the agent reported no installed PHP version: the polygon has php-fpm, a bare workstation does not',
    ).not.toHaveCount(0)
    await offered.first().click()

    await page.getByRole('button', { name: 'Create site' }).click()
    await expect(page).toHaveURL(/\/sites/, { timeout: HOST_OPERATION_TIMEOUT })
    await page.getByRole('link', { name: SITE_DOMAIN }).click()

    // The document root is the agent's answer, not the panel's guess: `create_site` resolves the
    // directory it actually made and reports THAT path back, which is what proves the site exists
    // on the host and not only in a row.
    await expect(page.getByRole('heading', { level: 1, name: SITE_DOMAIN })).toBeVisible()
    await expect(page.getByText(`/home/${ACCOUNT_NAME}/sites/${SITE_DOMAIN}`)).toBeVisible({
      timeout: HOST_OPERATION_TIMEOUT,
    })

    // --- the certificate ---------------------------------------------------------------------
    // Through the SSL TAB, in the browser, like everything else here. It used to be installed by
    // calling the panel's API directly, because the tab's API composable was still a seam that
    // rejected every call — so this spec was routing around a defect rather than driving the
    // product. The material is a self-signed pair generated for this run: a real Let's Encrypt
    // order cannot be satisfied from here, and inventing a success would make this spec lie about
    // the one thing it exists to establish.
    await page.getByRole('button', { name: 'SSL' }).click()
    await expect(page.getByText('No certificate installed')).toBeVisible({
      timeout: HOST_OPERATION_TIMEOUT,
    })
    await page.getByRole('button', { name: 'Install my own certificate' }).click()
    await page
      .getByLabel('Certificate chain (PEM)')
      .fill(process.env.MARAN_E2E_CERTIFICATE_PEM ?? '')
    await page.getByLabel('Private key (PEM)').fill(process.env.MARAN_E2E_PRIVATE_KEY_PEM ?? '')
    await page.getByRole('button', { name: 'Install certificate' }).click()

    // The tab's own list, read back from the panel, is the first confirmation: the certificate is
    // there because the panel says it is, not because a form submitted.
    await expect(page.getByText('Uploaded')).toBeVisible({ timeout: HOST_OPERATION_TIMEOUT })

    // And the Overview tab agrees. This is the assertion that ties the three layers together —
    // the SPA reading the panel, the panel reading its database, and the agent having written key
    // material to disk and made nginx accept a TLS block naming it.
    await page.reload()
    await expect(page.getByText('Installed', { exact: true })).toBeVisible({
      timeout: HOST_OPERATION_TIMEOUT,
    })
  })
})
