//! The [`SslHost`] that actually touches this machine.

use std::io::Write as _;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use maran_agent_core::agent_paths::AgentPaths;
use maran_agent_core::command_outcome::CommandOutcome;
use maran_agent_core::validation::system::name::AccountName;

use crate::safe_write::model::{ConfigFile, Reload, Validator};
use crate::safe_write::{ConfigHost, SafeWriteError, remove_config, write_config_set};
use crate::sites::log_sink::LogSink;
use crate::sites::model::log_tail_request::LogTailRequest;
use crate::sites::model::tail_end::TailEnd;
use crate::sites::{ProcessSiteHost, SiteCertificate, SiteHost, SiteMaintenanceHost, SitesOpError};
use crate::ssl::model::certificate_material::CertificateMaterial;
use crate::ssl::model::key_tool_outcome::KeyToolOutcome;
use crate::ssl::model::self_signed_request::SelfSignedRequest;
use crate::ssl::self_signed_marker::self_signed_marker;
use crate::ssl::ssl_host::SslHost;
use crate::ssl::ssl_op_error::SslOpError;

/// Mode of the directory holding a domain's certificate material.
///
/// Root only, all the way down: the key inside is readable by no one else, and
/// a directory an unprivileged process cannot even traverse means a mode
/// mistake on a file inside it is not immediately exploitable.
const MATERIAL_DIRECTORY_MODE: u32 = 0o700;

/// Mode of the private key file.
///
/// `0600`, root-owned. The one number in this file that is a security control
/// rather than tidiness.
const KEY_MODE: u32 = 0o600;

/// Mode of the certificate file.
///
/// A certificate is public — every visitor is handed it during the handshake —
/// so it is not a secret. It still lives in a `0700` directory, so this mode is
/// what the file says about itself rather than what protects it.
const CERTIFICATE_MODE: u32 = 0o644;

/// What a marker file says to whoever opens it.
///
/// Only its existence is ever tested; this is here so that an operator who finds
/// the file learns what it means without reading the agent's source.
const MARKER_CONTENT: &str =
    "This certificate was generated by maran as a placeholder and may be replaced.\n";

/// The openssl subcommand that generates a self-signed certificate.
const REQUEST_SUBCOMMAND: &str = "req";

/// Runs the real openssl, and writes the real certificate material — the one
/// place in this area that spawns a process or touches a file.
///
/// Deliberately the smallest piece of the area: every decision worth reviewing
/// lives in the operations, where it is tested against a fake. What is left
/// here is spawning, a `chmod`, and the delegation of everything about a site's
/// vhost to the site area's own host, so a certificate installation writes the
/// same file, the same way, that `create_site` writes.
pub struct ProcessSslHost {
    /// The site area's real host, which this one delegates every site
    /// operation to.
    ///
    /// Composition rather than a second implementation: `ProcessSiteHost`
    /// already reads a vhost, writes one through the protocol and resolves a
    /// path inside a home, and a copy of that here would be a second answer to
    /// each of those questions.
    sites: ProcessSiteHost,
}

impl ProcessSslHost {
    /// Creates the host.
    #[must_use]
    pub fn new() -> Self {
        Self {
            sites: ProcessSiteHost::new(),
        }
    }
}

impl Default for ProcessSslHost {
    fn default() -> Self {
        Self::new()
    }
}

impl ConfigHost for ProcessSslHost {
    /// Spawns `program` with `arguments` as an argv array.
    ///
    /// No shell is involved, at any point (rules/security.md item 3): the
    /// arguments reach `execve` one by one, so there is no command line for
    /// anything to re-parse. `program` comes from the `DistroAdapter`'s
    /// allow-list and never from a request.
    fn run(&self, program: &str, arguments: &[&str]) -> Result<CommandOutcome, SafeWriteError> {
        self.sites.run(program, arguments)
    }
}

impl SiteHost for ProcessSslHost {
    /// Delegates to the site area's host.
    fn read_config(&self, path: &Path) -> Result<Option<String>, SitesOpError> {
        self.sites.read_config(path)
    }

    /// Delegates to the site area's host.
    fn create_directories_as_account(
        &self,
        account: &AccountName,
        directories: &[&Path],
    ) -> Result<(), SitesOpError> {
        self.sites
            .create_directories_as_account(account, directories)
    }

    /// Delegates to the site area's host.
    fn write_config(
        &self,
        target: &Path,
        contents: &str,
        validator: &Validator<'_>,
        reload: &Reload<'_>,
    ) -> Result<(), SitesOpError> {
        self.sites.write_config(target, contents, validator, reload)
    }

    /// Delegates to the site area's host.
    fn remove_config(
        &self,
        target: &Path,
        validator: &Validator<'_>,
        reload: &Reload<'_>,
    ) -> Result<(), SitesOpError> {
        self.sites.remove_config(target, validator, reload)
    }

    /// Delegates to the site area's host.
    fn resolve_in_account_home(
        &self,
        account: &AccountName,
        relative: &Path,
    ) -> Result<PathBuf, SitesOpError> {
        self.sites.resolve_in_account_home(account, relative)
    }
}

impl SslHost for ProcessSslHost {
    /// Spawns `program` with the certificate on standard input and returns
    /// everything it said.
    fn run_with_certificate(
        &self,
        program: &str,
        arguments: &[&str],
        certificate_pem: &str,
    ) -> Result<CommandOutcome, SslOpError> {
        spawn_with_input(program, arguments, certificate_pem)
    }

    /// Spawns `program` with the private key on standard input and throws away
    /// everything it said but the exit status and the bytes to be compared.
    ///
    /// The stderr of this process is dropped HERE, in the one file that spawns
    /// anything, and never reaches a caller. That is the whole mechanism: an
    /// operation cannot attach what openssl printed about a key to an error,
    /// because by the time it holds the outcome there is nothing left to attach.
    fn run_with_private_key(
        &self,
        program: &str,
        arguments: &[&str],
        private_key_pem: &str,
    ) -> Result<KeyToolOutcome, SslOpError> {
        let outcome = spawn_with_input(program, arguments, private_key_pem)?;

        Ok(KeyToolOutcome::new(outcome.status == 0, outcome.stdout))
    }

    /// Reads the material, distinguishing "absent" from "unreadable".
    fn read_material(&self, path: &Path) -> Result<Option<String>, SslOpError> {
        match std::fs::read_to_string(path) {
            Ok(contents) => Ok(Some(contents)),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(_) => Err(SslOpError::MaterialWrite {
                reason: format!("could not read {}", path.display()),
            }),
        }
    }

    /// Writes both files as ONE change of the config-write protocol.
    ///
    /// Not two writes. On a renewal the vhost already names both files, so
    /// between two separate writes the pair on disk is mismatched — and
    /// `nginx -t` loads them: `SSL_CTX_use_PrivateKey_file` compares the key
    /// against the certificate and fails with `key values mismatch`. The first
    /// write's own validation would then fail and roll back, and every renewal
    /// on the host would be reported as a validation failure, with an nginx
    /// error saying precisely what `key_matches_certificate` had just proved
    /// false.
    ///
    /// `write_config_set` also sets each file's mode on the temporary file
    /// before the rename, so the key is `0600` from the moment its name exists —
    /// there is no window between a `create` and a `chmod` for it to be wider
    /// in, which is what a plain `File::create` would have.
    fn write_material(
        &self,
        certificate: &SiteCertificate,
        material: &CertificateMaterial,
        validator: &Validator<'_>,
        reload: &Reload<'_>,
    ) -> Result<(), SslOpError> {
        let directory =
            certificate
                .key_path()
                .parent()
                .ok_or_else(|| SslOpError::MaterialWrite {
                    reason: "the certificate path has no directory".to_owned(),
                })?;
        create_private_directory(directory)?;

        Ok(write_config_set(
            self,
            &[
                // The key first, so that a reader of this list sees the order
                // the files are prepared and renamed in. Both land before
                // anything is validated, so neither is ever alone.
                ConfigFile {
                    target: certificate.key_path(),
                    contents: material.private_key_pem(),
                    mode: KEY_MODE,
                },
                ConfigFile {
                    target: certificate.certificate_path(),
                    contents: material.certificate_pem(),
                    mode: CERTIFICATE_MODE,
                },
            ],
            validator,
            reload,
        )?)
    }

    /// Writes the marker, root-owned, at the certificate's own mode.
    ///
    /// A plain write and not the config-write protocol: nginx never reads this
    /// file, so there is nothing for `nginx -t` to have an opinion about and
    /// nothing a reload would pick up. Its content is a sentence for whoever
    /// finds it; only its EXISTENCE is ever tested.
    fn write_self_signed_marker(&self, path: &Path) -> Result<(), SslOpError> {
        std::fs::write(path, MARKER_CONTENT).map_err(|error| SslOpError::MaterialWrite {
            reason: format!("could not write {}: {error}", path.display()),
        })?;

        set_mode(path, CERTIFICATE_MODE)
    }

    /// Removes the marker, treating an absent one as the state already reached.
    fn remove_self_signed_marker(&self, path: &Path) -> Result<(), SslOpError> {
        match std::fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(SslOpError::MaterialWrite {
                reason: format!("could not remove {}: {error}", path.display()),
            }),
        }
    }

    /// Removes the certificate first and the key second.
    ///
    /// The mirror of the write order, and for the mirrored reason: what must
    /// not exist alone is a certificate whose key is gone, so the public half
    /// goes first and the secret half never outlives it.
    fn remove_material(
        &self,
        certificate: &SiteCertificate,
        validator: &Validator<'_>,
        reload: &Reload<'_>,
    ) -> Result<(), SslOpError> {
        remove_config(self, certificate.certificate_path(), validator, reload)?;
        remove_config(self, certificate.key_path(), validator, reload)?;
        // With the material, never after it: a marker outliving the files it
        // describes would describe whatever is written there next.
        self.remove_self_signed_marker(&self_signed_marker(certificate))?;

        // The now-empty directory, best effort: a directory left behind is
        // untidy, and a failure to remove it is not a reason to report a
        // removal that did happen as a failure.
        if let Some(directory) = certificate.key_path().parent() {
            let _ = std::fs::remove_dir(directory);
        }

        Ok(())
    }

    /// Generates the pair in a temporary directory inside the agent's own
    /// certificate store, reads both files back, and removes them.
    ///
    /// Inside the store and not inside the system temporary directory, because
    /// `/tmp` is world-traversable and shared with every account on the host:
    /// even for the second a key spends there, the only thing between it and a
    /// customer would be the directory's own mode. `TempDir` removes the
    /// directory when it is dropped, on every path out of this function.
    fn generate_material(
        &self,
        program: &str,
        request: &SelfSignedRequest,
    ) -> Result<CertificateMaterial, SslOpError> {
        let store = PathBuf::from(AgentPaths::CERTIFICATE_DIRECTORY);
        create_private_directory(&store)?;

        let workspace = tempfile::Builder::new()
            .prefix(".maran-self-signed-")
            .tempdir_in(&store)
            .map_err(|error| SslOpError::ToolUnavailable {
                reason: format!("could not create a working directory: {error}"),
            })?;
        create_private_directory(workspace.path())?;

        let key_path = workspace.path().join("privkey.pem");
        let certificate_path = workspace.path().join("fullchain.pem");
        let days = request.days.to_string();
        // Owned, and bound before the array: a `Cow` produced inside the array
        // literal would be dropped at the end of that statement, while the
        // array still borrowed it.
        let key_argument = key_path.to_string_lossy().into_owned();
        let certificate_argument = certificate_path.to_string_lossy().into_owned();
        let arguments = [
            REQUEST_SUBCOMMAND,
            "-x509",
            "-sha256",
            "-nodes",
            "-newkey",
            &request.key_specification,
            "-days",
            &days,
            "-subj",
            &request.subject,
            "-addext",
            &request.subject_alternative_name,
            "-keyout",
            &key_argument,
            "-out",
            &certificate_argument,
        ];

        let outcome =
            self.run(program, &arguments)
                .map_err(|error| SslOpError::ToolUnavailable {
                    reason: error.to_string(),
                })?;
        if outcome.status != 0 {
            // openssl's own diagnostics about a request it refused. No key
            // exists yet at this point that could be echoed: it would have been
            // written to the file it never produced.
            return Err(SslOpError::MalformedCertificate {
                reason: outcome.stderr,
            });
        }

        // openssl 3 creates a `-keyout` file at 0600, but "the version we
        // tested on does that" is not a protection. The mode is asserted rather
        // than assumed, while the file is still inside a directory nothing but
        // root can traverse.
        set_mode(&key_path, KEY_MODE)?;

        let read = |path: &Path| {
            std::fs::read_to_string(path).map_err(|_| SslOpError::ToolUnavailable {
                reason: "the generated certificate could not be read back".to_owned(),
            })
        };

        Ok(CertificateMaterial::new(
            &read(&certificate_path)?,
            &read(&key_path)?,
        ))
    }
}

impl SiteMaintenanceHost for ProcessSslHost {
    /// Delegates to the site area's host.
    ///
    /// The certificate operations never reload on their own — every one of them
    /// ends by rewriting a vhost through the write protocol, which validates and
    /// reloads for them. This exists because the SITES service is now handed
    /// this host rather than a bare [`ProcessSiteHost`]: deleting a site has to
    /// take the domain's certificate material with it, which needs an
    /// [`SslHost`], while the same service still offers the batching reload and
    /// the log tail. Composition again, rather than a second implementation of
    /// either.
    fn validate_and_reload(
        &self,
        validator: &Validator<'_>,
        reload: &Reload<'_>,
    ) -> Result<(), SitesOpError> {
        self.sites.validate_and_reload(validator, reload)
    }

    /// Delegates to the site area's host.
    fn tail_log(
        &self,
        request: &LogTailRequest,
        sink: &mut dyn LogSink,
    ) -> Result<TailEnd, SitesOpError> {
        self.sites.tail_log(request, sink)
    }
}

/// Creates `directory`, and every missing parent, owned by root and traversable
/// by nobody else.
///
/// The mode is set explicitly rather than left to `create_dir_all`, whose
/// result is `0o777 & !umask` and therefore depends on how the daemon happened
/// to be started. It is re-applied on every call, so a directory that already
/// exists at a laxer mode is corrected rather than accepted — and this is the
/// directory a private key lives in.
fn create_private_directory(directory: &Path) -> Result<(), SslOpError> {
    std::fs::create_dir_all(directory).map_err(|error| SslOpError::MaterialWrite {
        reason: format!("could not create {}: {error}", directory.display()),
    })?;

    set_mode(directory, MATERIAL_DIRECTORY_MODE)
}

/// Sets `path`'s mode, reporting a failure as a material-write failure.
///
/// A failure here is not cosmetic and is never ignored: the whole protection of
/// a private key on this host is its mode.
fn set_mode(path: &Path, mode: u32) -> Result<(), SslOpError> {
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode)).map_err(|error| {
        SslOpError::MaterialWrite {
            reason: format!("could not set the mode of {}: {error}", path.display()),
        }
    })
}

/// Spawns `program` with `arguments` and hands it `input` on standard input.
///
/// Shared by both `run_with_*` methods so there is one spawning sequence rather
/// than two that can drift; what differs between them is only how much of the
/// result the caller is allowed to see, and that is decided by their return
/// types.
///
/// The child's stdin is closed by dropping the handle before the wait: a tool
/// that reads to end-of-file — which every one of these does — would otherwise
/// wait forever for input that has already been written, and the agent would
/// wait with it.
///
/// # Errors
///
/// Returns [`SslOpError::ToolUnavailable`] when the program cannot be started,
/// its input cannot be delivered, or it cannot be waited for.
fn spawn_with_input(
    program: &str,
    arguments: &[&str],
    input: &str,
) -> Result<CommandOutcome, SslOpError> {
    let unavailable = |reason: String| SslOpError::ToolUnavailable { reason };

    let mut child = Command::new(program)
        .args(arguments)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| unavailable(format!("could not run {program}: {error}")))?;

    match child.stdin.take() {
        Some(mut stdin) => {
            // The write's failure is reported without its cause: the buffer
            // being written IS sometimes the private key, and an io error's
            // message is not a place to find out.
            let written = stdin.write_all(input.as_bytes());
            drop(stdin);
            written.map_err(|_| unavailable(format!("could not write to {program}")))?;
        }
        None => {
            return Err(unavailable(format!(
                "could not open the input of {program}"
            )));
        }
    }

    let output = child
        .wait_with_output()
        .map_err(|error| unavailable(format!("could not wait for {program}: {error}")))?;

    Ok(CommandOutcome {
        // -1 for a process killed by a signal: it did not exit, and reporting 0
        // would read as success to every caller.
        status: output.status.code().unwrap_or(-1),
        stdout: String::from_utf8_lossy(&output.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
    })
}

#[cfg(test)]
#[path = "../tests/ssl/process_ssl_host_tests.rs"]
mod tests;
