// <auto-generated />
using System;
using Maran.Modules.Accounts.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maran.Modules.Accounts.Persistence.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    partial class AccountsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accounts")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maran.Modules.Accounts.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_Name");

                    b.HasIndex("PlanId");

                    b.HasIndex("PrimaryDomain")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_PrimaryDomain");

                    b.ToTable("Accounts", "accounts");
                });

            modelBuilder.Entity("Maran.Modules.Accounts.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiskQuotaMb")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayNameKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MaxDatabases")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFtpUsers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSites")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Plans_DisplayNameKey");

                    b.ToTable("Plans", "accounts");
                });

            modelBuilder.Entity("Maran.Modules.Accounts.Domain.Account", b =>
                {
                    b.HasOne("Maran.Modules.Accounts.Domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_Plans_PlanId");
                });
#pragma warning restore 612, 618
        }
    }
}
